version: "3.8"

services:
  arangodb:
    image: arangodb:3.7
    container_name: sample_arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=somepassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  app:
    build: .
    container_name: sample_back
    ports:
    - "8000:8000"
    depends_on:
      - "arangodb"
    environment:
      - APP_arangodb_url=http://sample_arangodb:8529

  youtrack:
    image: jetbrains/youtrack:2020.6.1099
    ports:
      - "10100:8080"
    volumes:
      - ./youtrack/youtrack_data:/opt/youtrack/data
      - ./youtrack/youtrack_conf:/opt/youtrack/conf
      - ./youtrack/youtrack_logs:/opt/youtrack/logs
      - ./youtrack/youtrack_backups:/opt/youtrack/backups

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

