version: "3.8"

services:
  arangodb:
    image: arangodb:3.7
    container_name: sample_arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=somepassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  app:
    build: .
    container_name: sample_back
    ports:
    - "8000:8000"
    depends_on:
      - "arangodb"
    environment:
      - APP_arangodb_url=http://sample_arangodb:8529
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

