[package]
name = "gitlab-tools"
version = "0.1.0"
authors = ["Sergey <som>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# endpoints
gitlab = "*"

git-utils = { path = "../utils/git-utils" }